add file transfer script and README for web server task

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,17 +1,21 @@
 #!/usr/bin/env bash
-# This script transfers a file to a remote server using scp with disabled strict host key checking
+# This script transfers a file to a remote server's home directory using scp with disabled host key checking
 
-# Check if the number of arguments is less than 4
-if [ "$#" -lt 4 ]; then
+if [ $# -lt 4 ]; then
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-# Assign arguments to variables
-FILE="$1"
+PATH_TO_FILE="$1"
 IP="$2"
-USER="$3"
-KEY="$4"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
 
-# Transfer the file
-scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+if [ $? -eq 0 ]; then
+    echo "File transfer completed successfully"
+else
+    echo "File transfer failed"
+    exit 1
+fi
